# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User2',
        ),
    ]
