# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20171128_1807'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User1',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='User12',
        ),
    ]
